// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.0;

import {KoalaBearExt4} from "../../lib/sol-whir-p3/field/KoalaBearExt4.sol";

/// The last layer of `verify_batch`: the constraint identity.
///
/// Per instance, after the opening argument has proven the values of every trace,
/// permutation and quotient polynomial at the out-of-domain point `zeta`, the
/// verifier checks
///
/// ```text
/// fold(alpha, constraints(zeta)) * inv_vanishing(zeta) == quotient(zeta)
/// ```
///
/// where `fold` is the Horner combination `acc = acc*alpha + C_g` over the AIR's
/// constraints in emission order. The settlement AIRs are generated by the prover
/// (Poseidon2 / recompose / statement tables), so the constraints are trusted
/// setup data: the export in `tests/vectors/constraint_identity_vectors.json`
/// flattens each constraint to a post-order DAG over this library's op codes,
/// shared subtrees emitted once. This contract is the DAG interpreter.
///
/// All arithmetic is in the packed quartic extension (`KoalaBearExt4`, x^4 = 3).
/// The selector leaves divide by `zh`, `s1 = u - 1` and `s2 = u - h_inv` where
/// `u = zeta * inv_shift`; those denominators depend only on `zeta` and the
/// domain, so the contract inverts three extension elements per instance (plus
/// one for `inv_vanishing`) and shares them across every constraint.
///
/// The quotient recompose divides by `Z_j(first_i)`, a domain-only constant, so
/// the trusted setup ships `invD_i = (prod_{j != i} Z_j(first_i))^-1` and the
/// runtime path needs no inversion there.
library ConstraintIdentity {
    using KoalaBearExt4 for uint256;

    /// Node op codes. Leaves resolve to an extension value; operators consume
    /// one or two earlier node indices (post-order: operands precede results).
    uint8 internal constant OP_CONST_BASE = 0;
    uint8 internal constant OP_CONST_EXT = 1;
    uint8 internal constant OP_MAIN_LOCAL = 2;
    uint8 internal constant OP_MAIN_NEXT = 3;
    uint8 internal constant OP_PRE_LOCAL = 4;
    uint8 internal constant OP_PRE_NEXT = 5;
    uint8 internal constant OP_PERM_LOCAL = 6;
    uint8 internal constant OP_PERM_NEXT = 7;
    uint8 internal constant OP_PERM_CHALLENGE = 8;
    uint8 internal constant OP_PERM_VALUE = 9;
    uint8 internal constant OP_PUBLIC = 10;
    uint8 internal constant OP_PERIODIC = 11;
    uint8 internal constant OP_IS_FIRST = 12;
    uint8 internal constant OP_IS_LAST = 13;
    uint8 internal constant OP_IS_TRANSITION = 14;
    uint8 internal constant OP_ADD = 15;
    uint8 internal constant OP_SUB = 16;
    uint8 internal constant OP_MUL = 17;
    uint8 internal constant OP_NEG = 18;

    /// A base-field value lifted into the extension: only the first limb is set.
    function lift(uint256 x) internal pure returns (uint256) {
        return x << 224;
    }

    /// The opened values one instance's constraint program consumes: everything
    /// the opening argument returns plus the transcript challenges, all packed
    /// extension elements (public values are base elements, canonical u32).
    struct Opened {
        uint256[] mainLocal;
        uint256[] mainNext;
        uint256[] preLocal;
        uint256[] preNext;
        uint256[] permLocal;
        uint256[] permNext;
        uint256[] permChallenges;
        uint256[] permValues;
        uint256[] publicValues;
        uint256[] periodicValues;
    }

    /// The trusted-setup constraint program for one instance. `nodes` is flat
    /// triples `[op, a, b]`; `roots[g]` is the node index of constraint `g` in
    /// emission order, the order the Horner fold walks.
    struct Program {
        uint256[] nodes;
        uint256[] baseConsts;
        uint256[] extConsts;
        uint256[] roots;
    }

    /// One quotient chunk domain: `log_size` and the domain shift, both base
    /// field. The vanishing polynomial is `(x * inv_shift)^(2^log_size) - 1`.
    struct ChunkDomain {
        uint256 logSize;
        uint256 shift;
        uint256 invShift;
    }

    /// The Lagrange selectors of a trace domain at the out-of-domain point. For the
    /// coset `gH` with `u = zeta * g^-1` and `zh = u^(2^log_size) - 1`:
    /// `is_first = zh / (u - 1)`, `is_last = zh / (u - h_inv)`,
    /// `is_transition = u - h_inv` (the polynomial vanishing on the last row) and
    /// `inv_vanishing = 1 / zh`.
    struct Selectors {
        uint256 isFirst;
        uint256 isLast;
        uint256 isTransition;
        uint256 invVanishing;
    }

    /// The selector denominators depend only on `zeta` and the domain, so the whole
    /// constraint layer pays three extension inversions per instance, shared by every
    /// constraint, plus one more for `inv_vanishing`.
    function selectors(
        uint256 zeta,
        uint256 traceInvShift,
        uint256 traceLogSize,
        uint256 traceHInv
    ) internal pure returns (Selectors memory out) {
        uint256 u = zeta.mulBase(traceInvShift);
        uint256 zh = pow2(u, traceLogSize).sub(KoalaBearExt4.ONE);
        uint256 s1 = u.sub(KoalaBearExt4.ONE);
        uint256 s2 = u.sub(KoalaBearExt4.fromBase(traceHInv));
        out.isFirst = zh.mul(s1.inv());
        out.isLast = zh.mul(s2.inv());
        out.isTransition = s2;
        out.invVanishing = zh.inv();
    }

    /// Evaluate every node of the program at `zeta` and fold the roots with `alpha`
    /// by Horner (`acc = acc*alpha + C_g` in emission order). The caller multiplies
    /// the fold by `selectors.invVanishing` and compares against `quotient`.
    function foldConstraints(
        Program memory prog,
        Opened memory opened,
        Selectors memory sels,
        uint256 alpha
    ) internal pure returns (uint256) {
        uint256 isFirst = sels.isFirst;
        uint256 isLast = sels.isLast;
        uint256 s2 = sels.isTransition;

        uint256 n = prog.nodes.length / 3;
        uint256[] memory stack = new uint256[](n);
        for (uint256 i = 0; i < n; ++i) {
            uint256 base = 3 * i;
            // forge-lint: disable-next-line(unsafe-typecast)
            uint8 op = uint8(prog.nodes[base]);
            uint256 a = prog.nodes[base + 1];
            uint256 b = prog.nodes[base + 2];
            if (op == OP_ADD) {
                stack[i] = stack[a].add(stack[b]);
            } else if (op == OP_SUB) {
                stack[i] = stack[a].sub(stack[b]);
            } else if (op == OP_MUL) {
                stack[i] = stack[a].mul(stack[b]);
            } else if (op == OP_NEG) {
                stack[i] = uint256(0).sub(stack[a]);
            } else if (op == OP_CONST_BASE) {
                stack[i] = lift(prog.baseConsts[a]);
            } else if (op == OP_CONST_EXT) {
                stack[i] = prog.extConsts[a];
            } else if (op == OP_MAIN_LOCAL) {
                stack[i] = opened.mainLocal[a];
            } else if (op == OP_MAIN_NEXT) {
                stack[i] = opened.mainNext[a];
            } else if (op == OP_PRE_LOCAL) {
                stack[i] = opened.preLocal[a];
            } else if (op == OP_PRE_NEXT) {
                stack[i] = opened.preNext[a];
            } else if (op == OP_PERM_LOCAL) {
                stack[i] = opened.permLocal[a];
            } else if (op == OP_PERM_NEXT) {
                stack[i] = opened.permNext[a];
            } else if (op == OP_PERM_CHALLENGE) {
                stack[i] = opened.permChallenges[a];
            } else if (op == OP_PERM_VALUE) {
                stack[i] = opened.permValues[a];
            } else if (op == OP_PUBLIC) {
                stack[i] = lift(opened.publicValues[a]);
            } else if (op == OP_PERIODIC) {
                stack[i] = opened.periodicValues[a];
            } else if (op == OP_IS_FIRST) {
                stack[i] = isFirst;
            } else if (op == OP_IS_LAST) {
                stack[i] = isLast;
            } else if (op == OP_IS_TRANSITION) {
                stack[i] = s2;
            } else {
                revert("bad op");
            }
        }

        uint256 acc = 0;
        for (uint256 g = 0; g < prog.roots.length; ++g) {
            acc = acc.mul(alpha).add(stack[prog.roots[g]]);
        }
        return acc;
    }

    /// `Z_j(zeta)` for each quotient chunk domain: `(zeta * inv_shift_j)^(2^log_j) - 1`.
    /// No inversion: the cross-domain denominators are the trusted `invD` constants.
    function chunkVanishings(uint256 zeta, ChunkDomain[] memory domains)
        internal
        pure
        returns (uint256[] memory out)
    {
        out = new uint256[](domains.length);
        for (uint256 j = 0; j < domains.length; ++j) {
            out[j] =
                pow2(zeta.mulBase(domains[j].invShift), domains[j].logSize).sub(KoalaBearExt4.ONE);
        }
    }

    /// Recompose `quotient(zeta)` from the chunk openings. `invD[i]` is the
    /// trusted `(prod_{j != i} Z_j(first_i))^-1`; `quotientChunks[i]` is the
    /// i-th chunk evaluated at `zeta`, packed.
    function recomposeQuotient(
        uint256[] memory quotientChunks,
        ChunkDomain[] memory domains,
        uint256[] memory invD,
        uint256 zeta
    ) internal pure returns (uint256) {
        uint256 k = quotientChunks.length;
        uint256[] memory zstars = chunkVanishings(zeta, domains);
        uint256 sum = 0;
        for (uint256 i = 0; i < k; ++i) {
            uint256 prod = KoalaBearExt4.ONE;
            for (uint256 j = 0; j < k; ++j) {
                if (j != i) {
                    prod = prod.mul(zstars[j]);
                }
            }
            sum = sum.add(quotientChunks[i].mul(prod).mul(invD[i]));
        }
        return sum;
    }

    /// `x^(2^log)` by repeated squaring, matching `exp_power_of_2`.
    function pow2(uint256 x, uint256 log) internal pure returns (uint256) {
        uint256 v = x;
        for (uint256 i = 0; i < log; ++i) {
            v = v.square();
        }
        return v;
    }
}
