// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.0;

import {KoalaBearExt4} from "../../lib/sol-whir-p3/field/KoalaBearExt4.sol";

/// The last layer of `verify_batch`: the constraint identity.
///
/// Per instance, after the opening argument has proven the values of every trace,
/// permutation and quotient polynomial at the out-of-domain point `zeta`, the
/// verifier checks
///
/// ```text
/// fold(alpha, constraints(zeta)) * inv_vanishing(zeta) == quotient(zeta)
/// ```
///
/// where `fold` is the Horner combination `acc = acc*alpha + C_g` over the AIR's
/// constraints in emission order. The settlement AIRs are generated by the prover
/// (Poseidon2 / recompose / statement tables), so the constraints are trusted
/// setup data: the export in `tests/vectors/constraint_identity_vectors.json`
/// flattens each constraint to a post-order DAG over this library's op codes,
/// shared subtrees emitted once. This contract is the DAG interpreter.
///
/// All arithmetic is in the packed quartic extension (`KoalaBearExt4`, x^4 = 3).
/// The selector leaves divide by `zh`, `s1 = u - 1` and `s2 = u - h_inv` where
/// `u = zeta * inv_shift`; those denominators depend only on `zeta` and the
/// domain, so the contract inverts three extension elements per instance (plus
/// one for `inv_vanishing`) and shares them across every constraint.
///
/// The quotient recompose divides by `Z_j(first_i)`, a domain-only constant, so
/// the trusted setup ships `invD_i = (prod_{j != i} Z_j(first_i))^-1` and the
/// runtime path needs no inversion there.
library ConstraintIdentity {
    using KoalaBearExt4 for uint256;

    /// Node op codes. Leaves resolve to an extension value; operators consume
    /// one or two earlier node indices (post-order: operands precede results).
    uint8 internal constant OP_CONST_BASE = 0;
    uint8 internal constant OP_CONST_EXT = 1;
    uint8 internal constant OP_MAIN_LOCAL = 2;
    uint8 internal constant OP_MAIN_NEXT = 3;
    uint8 internal constant OP_PRE_LOCAL = 4;
    uint8 internal constant OP_PRE_NEXT = 5;
    uint8 internal constant OP_PERM_LOCAL = 6;
    uint8 internal constant OP_PERM_NEXT = 7;
    uint8 internal constant OP_PERM_CHALLENGE = 8;
    uint8 internal constant OP_PERM_VALUE = 9;
    uint8 internal constant OP_PUBLIC = 10;
    uint8 internal constant OP_PERIODIC = 11;
    uint8 internal constant OP_IS_FIRST = 12;
    uint8 internal constant OP_IS_LAST = 13;
    uint8 internal constant OP_IS_TRANSITION = 14;
    uint8 internal constant OP_ADD = 15;
    uint8 internal constant OP_SUB = 16;
    uint8 internal constant OP_MUL = 17;
    uint8 internal constant OP_NEG = 18;

    /// A base-field value lifted into the extension: only the first limb is set.
    function lift(uint256 x) internal pure returns (uint256) {
        return x << 224;
    }

    /// The opened values one instance's constraint program consumes: everything
    /// the opening argument returns plus the transcript challenges, all packed
    /// extension elements (public values are base elements, canonical u32).
    struct Opened {
        uint256[] mainLocal;
        uint256[] mainNext;
        uint256[] preLocal;
        uint256[] preNext;
        uint256[] permLocal;
        uint256[] permNext;
        uint256[] permChallenges;
        uint256[] permValues;
        uint256[] publicValues;
        uint256[] periodicValues;
    }

    /// The trusted-setup constraint program for one instance. `nodes` is flat
    /// triples `[op, a, b]`; `roots[g]` is the node index of constraint `g` in
    /// emission order, the order the Horner fold walks.
    struct Program {
        /// Decoded node words; EMPTY when `nodesCdBase` is set (the production
        /// path keeps the node program in calldata - copying 88 KB into memory
        /// costs ~490 gas/word in expansion alone at the heap high-water).
        uint256[] nodes;
        /// Absolute calldata byte offset of the first node word, or 0 to read
        /// `nodes` from memory (JSON-driven tests).
        uint256 nodesCdBase;
        /// Node word count (3 per op) when reading from calldata.
        uint256 nodesLen;
        uint256[] baseConsts;
        uint256[] extConsts;
        uint256[] roots;
    }

    /// One quotient chunk domain: `log_size` and the domain shift, both base
    /// field. The vanishing polynomial is `(x * inv_shift)^(2^log_size) - 1`.
    struct ChunkDomain {
        uint256 logSize;
        uint256 shift;
        uint256 invShift;
    }

    /// The Lagrange selectors of a trace domain at the out-of-domain point. For the
    /// coset `gH` with `u = zeta * g^-1` and `zh = u^(2^log_size) - 1`:
    /// `is_first = zh / (u - 1)`, `is_last = zh / (u - h_inv)`,
    /// `is_transition = u - h_inv` (the polynomial vanishing on the last row) and
    /// `inv_vanishing = 1 / zh`.
    struct Selectors {
        uint256 isFirst;
        uint256 isLast;
        uint256 isTransition;
        uint256 invVanishing;
    }

    /// The selector denominators depend only on `zeta` and the domain, so the whole
    /// constraint layer pays three extension inversions per instance, shared by every
    /// constraint, plus one more for `inv_vanishing`.
    function selectors(
        uint256 zeta,
        uint256 traceInvShift,
        uint256 traceLogSize,
        uint256 traceHInv
    ) internal pure returns (Selectors memory out) {
        uint256 u = zeta.mulBase(traceInvShift);
        uint256 zh = pow2(u, traceLogSize).sub(KoalaBearExt4.ONE);
        uint256 s1 = u.sub(KoalaBearExt4.ONE);
        uint256 s2 = u.sub(KoalaBearExt4.fromBase(traceHInv));
        out.isFirst = zh.mul(s1.inv());
        out.isLast = zh.mul(s2.inv());
        out.isTransition = s2;
        out.invVanishing = zh.inv();
    }

    /// Evaluate every node of the program at `zeta` and fold the roots with `alpha`
    /// by Horner (`acc = acc*alpha + C_g` in emission order). The caller multiplies
    /// the fold by `selectors.invVanishing` and compares against `quotient`.
    function foldConstraints(
        Program memory prog,
        Opened memory opened,
        Selectors memory sels,
        uint256 alpha
    ) internal pure returns (uint256) {
        uint256 n = prog.nodesCdBase == 0 ? prog.nodes.length / 3 : prog.nodesLen / 3;
        uint256[] memory stack = new uint256[](n);
        // Batch 38: the whole node loop in one Yul block. The Solidity
        // if/else-if chain cost ~10 compares per node over 19 op codes; the
        // Yul switch compiles to a jump table, and the arithmetic arms are
        // register-fused (unpack once, one mod per lane, no call frame).
        // The leaf arms exploit the layout: Opened's ten arrays sit at
        // (op-2)*32 for ops 2..11 and Selectors' first three fields at
        // (op-12)*32 for ops 12..14, so one indexed mload covers all of
        // them. Program: nodes@0 baseConsts@96 extConsts@128.
        assembly ("memory-safe") {
            let P := 0x7f000001
            let M := 0xffffffff
            let W := 3
            let sp := add(stack, 32)
            let cdb := mload(add(prog, 32))
            for { let idx := 0 } lt(idx, n) { idx := add(idx, 1) } {
                let op := 0
                let x := 0
                let y := 0
                switch cdb
                case 0 {
                    let np := add(add(mload(prog), 32), mul(idx, 96))
                    op := mload(np)
                    x := mload(add(np, 32))
                    y := mload(add(np, 64))
                }
                default {
                    // Three LE u32 words per node, one calldataload: the node
                    // is 12 bytes, fully inside one word. LE decode = byte
                    // swap of the big-endian slice (same recipe as _arr).
                    let w := calldataload(add(cdb, mul(idx, 12)))
                    op := shr(248, w)
                    x := and(shr(192, w), 0xffffffff)
                    x := or(and(shr(8, x), 0x00ff00ff), and(shl(8, x), 0xff00ff00))
                    x := or(and(shr(16, x), 0x0000ffff), and(shl(16, x), 0xffff0000))
                    y := and(shr(160, w), 0xffffffff)
                    y := or(and(shr(8, y), 0x00ff00ff), and(shl(8, y), 0xff00ff00))
                    y := or(and(shr(16, y), 0x0000ffff), and(shl(16, y), 0xffff0000))
                }
                let v := 0
                switch op
                case 15 {
                    if or(iszero(lt(x, n)), iszero(lt(y, n))) { mstore(0, 0x48ef0e01) revert(0, 4) }
                    let va := mload(add(sp, mul(x, 32)))
                    let vb := mload(add(sp, mul(y, 32)))
                    let x0 := mod(add(shr(224, va), shr(224, vb)), P)
                    let x1 := mod(add(and(shr(192, va), M), and(shr(192, vb), M)), P)
                    let x2 := mod(add(and(shr(160, va), M), and(shr(160, vb), M)), P)
                    let x3 := mod(add(and(shr(128, va), M), and(shr(128, vb), M)), P)
                    v := or(or(shl(224, x0), shl(192, x1)), or(shl(160, x2), shl(128, x3)))
                }
                case 16 {
                    if or(iszero(lt(x, n)), iszero(lt(y, n))) { mstore(0, 0x48ef0e01) revert(0, 4) }
                    let va := mload(add(sp, mul(x, 32)))
                    let vb := mload(add(sp, mul(y, 32)))
                    let x0 := mod(add(shr(224, va), sub(P, shr(224, vb))), P)
                    let x1 := mod(add(and(shr(192, va), M), sub(P, and(shr(192, vb), M))), P)
                    let x2 := mod(add(and(shr(160, va), M), sub(P, and(shr(160, vb), M))), P)
                    let x3 := mod(add(and(shr(128, va), M), sub(P, and(shr(128, vb), M))), P)
                    v := or(or(shl(224, x0), shl(192, x1)), or(shl(160, x2), shl(128, x3)))
                }
                case 17 {
                    if or(iszero(lt(x, n)), iszero(lt(y, n))) { mstore(0, 0x48ef0e01) revert(0, 4) }
                    let va := mload(add(sp, mul(x, 32)))
                    let vb := mload(add(sp, mul(y, 32)))
                    let a0 := shr(224, va)
                    let a1 := and(shr(192, va), M)
                    let a2 := and(shr(160, va), M)
                    let a3 := and(shr(128, va), M)
                    let b0 := shr(224, vb)
                    let b1 := and(shr(192, vb), M)
                    let b2 := and(shr(160, vb), M)
                    let b3 := and(shr(128, vb), M)
                    let u0 := add(mul(a0, b0), mul(W, add(add(mul(a1, b3), mul(a2, b2)), mul(a3, b1))))
                    let u1 := add(add(mul(a0, b1), mul(a1, b0)), mul(W, add(mul(a2, b3), mul(a3, b2))))
                    let u2 := add(add(add(mul(a0, b2), mul(a1, b1)), mul(a2, b0)), mul(W, mul(a3, b3)))
                    let u3 := add(add(add(mul(a0, b3), mul(a1, b2)), mul(a2, b1)), mul(a3, b0))
                    v := or(or(shl(224, mod(u0, P)), shl(192, mod(u1, P))), or(shl(160, mod(u2, P)), shl(128, mod(u3, P))))
                }
                case 18 {
                    if iszero(lt(x, n)) { mstore(0, 0x48ef0e01) revert(0, 4) }
                    let va := mload(add(sp, mul(x, 32)))
                    let x0 := mod(sub(P, shr(224, va)), P)
                    let x1 := mod(sub(P, and(shr(192, va), M)), P)
                    let x2 := mod(sub(P, and(shr(160, va), M)), P)
                    let x3 := mod(sub(P, and(shr(128, va), M)), P)
                    v := or(or(shl(224, x0), shl(192, x1)), or(shl(160, x2), shl(128, x3)))
                }
                case 0 {
                    let arr := mload(add(prog, 96))
                    if iszero(lt(x, mload(arr))) { mstore(0, 0x48ef0e01) revert(0, 4) }
                    v := shl(224, mload(add(add(arr, 32), mul(x, 32))))
                }
                case 1 {
                    let arr := mload(add(prog, 128))
                    if iszero(lt(x, mload(arr))) { mstore(0, 0x48ef0e01) revert(0, 4) }
                    v := mload(add(add(arr, 32), mul(x, 32)))
                }
                default {
                    switch op
                    case 12 { v := mload(sels) }
                    case 13 { v := mload(add(sels, 32)) }
                    case 14 { v := mload(add(sels, 64)) }
                    default {
                        switch op
                        case 10 {
                            let arr := mload(add(opened, 256))
                            if iszero(lt(x, mload(arr))) { mstore(0, 0x48ef0e01) revert(0, 4) }
                            v := shl(224, mload(add(add(arr, 32), mul(x, 32))))
                        }
                        default {
                            if or(lt(op, 2), gt(op, 11)) { mstore(0, 0x48ef0e01) revert(0, 4) }
                            let arr := mload(add(opened, mul(sub(op, 2), 32)))
                            if iszero(lt(x, mload(arr))) { mstore(0, 0x48ef0e01) revert(0, 4) }
                            v := mload(add(add(arr, 32), mul(x, 32)))
                        }
                    }
                }
                mstore(add(sp, mul(idx, 32)), v)
            }
        }

        uint256 acc = 0;
        for (uint256 g = 0; g < prog.roots.length; ++g) {
            acc = acc.mul(alpha).add(stack[prog.roots[g]]);
        }
        return acc;
    }

    /// `Z_j(zeta)` for each quotient chunk domain: `(zeta * inv_shift_j)^(2^log_j) - 1`.
    /// No inversion: the cross-domain denominators are the trusted `invD` constants.
    function chunkVanishings(uint256 zeta, ChunkDomain[] memory domains)
        internal
        pure
        returns (uint256[] memory out)
    {
        out = new uint256[](domains.length);
        for (uint256 j = 0; j < domains.length; ++j) {
            out[j] =
                pow2(zeta.mulBase(domains[j].invShift), domains[j].logSize).sub(KoalaBearExt4.ONE);
        }
    }

    /// Recompose `quotient(zeta)` from the chunk openings. `invD[i]` is the
    /// trusted `(prod_{j != i} Z_j(first_i))^-1`; `quotientChunks[i]` is the
    /// i-th chunk evaluated at `zeta`, packed.
    function recomposeQuotient(
        uint256[] memory quotientChunks,
        ChunkDomain[] memory domains,
        uint256[] memory invD,
        uint256 zeta
    ) internal pure returns (uint256) {
        uint256 k = quotientChunks.length;
        uint256[] memory zstars = chunkVanishings(zeta, domains);
        uint256 sum = 0;
        for (uint256 i = 0; i < k; ++i) {
            uint256 prod = KoalaBearExt4.ONE;
            for (uint256 j = 0; j < k; ++j) {
                if (j != i) {
                    prod = prod.mul(zstars[j]);
                }
            }
            sum = sum.add(quotientChunks[i].mul(prod).mul(invD[i]));
        }
        return sum;
    }

    /// `x^(2^log)` by repeated squaring, matching `exp_power_of_2`.
    function pow2(uint256 x, uint256 log) internal pure returns (uint256) {
        uint256 v = x;
        for (uint256 i = 0; i < log; ++i) {
            v = v.square();
        }
        return v;
    }
}
