// SPDX-License-Identifier: MIT
// GENERATED by `prover::fixed_config::FixedSchedule::to_solidity`.
// DO NOT EDIT BY HAND. Regenerate with:
//     cargo test -p prover fixed_config -- --ignored --nocapture
//
// The settlement WHIR schedule, extracted from the `WhirConfig` the prover
// actually runs on. Every parameter the on-chain verifier needs is here,
// because a parameter the verifier guesses is a parameter it can get wrong
// without any test noticing.
//
// Source of truth: `p3_whir::parameters::WhirConfig` accessors, read by
// `FixedSchedule::from_whir_config`. Nothing in this file is transcribed.
//
// Shape borrowed from `ethereum/sol-whir-p3`: flat scalar constants for
// the schedule-level parameters, and a struct plus an unrolled index
// accessor for the per-round ones, because Solidity has no constant
// value-type arrays.
pragma solidity ^0.8.28;

/// Generated WHIR schedule constants for the settlement verifier.
library WhirFixedConfig {
    /// One WHIR round's parameters. Mirrors `RoundSchedule` in
    /// `crates/prover/src/fixed_config.rs`, which mirrors
    /// `p3_whir::parameters::RoundConfig`.
    struct RoundConfig {
        uint256 powBits;
        uint256 foldingPowBits;
        uint256 numQueries;
        uint256 oodSamples;
        uint256 numVariables;
        uint256 foldingFactor;
        uint256 logInvRate;
        uint256 domainSize;
        uint256 logFoldedDomainSize;
    }

    /// Number of variables in the original trace.
    uint256 internal constant NUM_VARIABLES = 25;

    /// Maximum two-adic domain size the field supports.
    uint256 internal constant MAX_LOG_DOMAIN_SIZE = 24;

    /// OOD samples drawn against the initial commitment.
    uint256 internal constant COMMITMENT_OOD_SAMPLES = 2;

    /// PoW bits required before the first folding round.
    uint256 internal constant STARTING_FOLDING_POW_BITS = 11;

    /// Queries in the terminal STIR test.
    uint256 internal constant TERMINAL_NUM_QUERIES = 12;

    /// PoW bits for the terminal test.
    uint256 internal constant TERMINAL_POW_BITS = 19;

    /// Sumcheck rounds on the final polynomial.
    uint256 internal constant FINAL_SUMCHECK_ROUNDS = 5;

    /// PoW bits on the final folding sumcheck.
    uint256 internal constant FINAL_FOLDING_POW_BITS = 0;

    /// Log inverse rate at the start of folding.
    uint256 internal constant STARTING_LOG_INV_RATE = 1;

    /// Target security level in bits.
    uint256 internal constant SECURITY_LEVEL = 96;

    /// Global PoW bits.
    uint256 internal constant POW_BITS = 23;

    /// Number of interactive folding rounds.
    uint256 internal constant N_ROUNDS = 4;

    /// Final-round parameters.
    uint256 internal constant FINAL_POW_BITS = 19;
    uint256 internal constant FINAL_NUM_QUERIES = 12;
    uint256 internal constant FINAL_FOLDING_FACTOR = 4;
    uint256 internal constant FINAL_NUM_VARIABLES = 5;
    uint256 internal constant FINAL_LOG_INV_RATE = 13;
    uint256 internal constant FINAL_DOMAIN_SIZE = 4194304;
    uint256 internal constant FINAL_LOG_FOLDED_DOMAIN_SIZE = 18;

    /// Total STIR queries across every round plus the terminal test.
    ///
    /// This is the number that drives proof size almost linearly: each
    /// query is a Merkle path over the Keccak tree. See D-038.
    uint256 internal constant TOTAL_QUERIES = 257;

    /// The folding factor applied at fold step `index`.
    ///
    /// Reverts past the end rather than returning a default: a caller that
    /// runs off the schedule is asking a question the schedule does not
    /// answer, and silently returning 0 would fold nothing while looking
    /// like it folded.
    function foldingSchedule(uint256 index) internal pure returns (uint256) {
        if (index == 0) {
            return 4;
        }
        if (index == 1) {
            return 4;
        }
        if (index == 2) {
            return 4;
        }
        if (index == 3) {
            return 4;
        }
        if (index == 4) {
            return 4;
        }
        revert("FOLD_INDEX");
    }

    /// The parameters of WHIR round `index`, in `[0, N_ROUNDS)`.
    function roundConfig(uint256 index) internal pure returns (RoundConfig memory) {
        if (index == 0) {
            return RoundConfig({ powBits: 23, foldingPowBits: 13, numQueries: 170, oodSamples: 2, numVariables: 21, foldingFactor: 4, logInvRate: 4, domainSize: 67108864, logFoldedDomainSize: 22 });
        }
        if (index == 1) {
            return RoundConfig({ powBits: 23, foldingPowBits: 15, numQueries: 38, oodSamples: 2, numVariables: 17, foldingFactor: 4, logInvRate: 7, domainSize: 33554432, logFoldedDomainSize: 21 });
        }
        if (index == 2) {
            return RoundConfig({ powBits: 21, foldingPowBits: 17, numQueries: 22, oodSamples: 2, numVariables: 13, foldingFactor: 4, logInvRate: 10, domainSize: 16777216, logFoldedDomainSize: 20 });
        }
        if (index == 3) {
            return RoundConfig({ powBits: 23, foldingPowBits: 19, numQueries: 15, oodSamples: 2, numVariables: 9, foldingFactor: 4, logInvRate: 13, domainSize: 8388608, logFoldedDomainSize: 19 });
        }
        revert("ROUND_INDEX");
    }

    /// The final round's parameters, in the same struct shape so the
    /// verifier can treat every round uniformly.
    function finalRoundConfig() internal pure returns (RoundConfig memory) {
        return RoundConfig({
            powBits: FINAL_POW_BITS,
            foldingPowBits: FINAL_FOLDING_POW_BITS,
            numQueries: FINAL_NUM_QUERIES,
            oodSamples: 0,
            numVariables: FINAL_NUM_VARIABLES,
            foldingFactor: FINAL_FOLDING_FACTOR,
            logInvRate: FINAL_LOG_INV_RATE,
            domainSize: FINAL_DOMAIN_SIZE,
            logFoldedDomainSize: FINAL_LOG_FOLDED_DOMAIN_SIZE
        });
    }
}
