// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {WhirVerifier} from "../src/verifier/WhirVerifier.sol";
import {TerminalWeight} from "../src/verifier/TerminalWeight.sol";
import {ShieldedPool} from "../src/ShieldedPool.sol";

/// The whole point, on one screen: a real shielded block - one client transfer,
/// a real SPHINCS+ spend of a funded note, recursed into the block circuit and
/// settled under the Keccak WHIR config - verifies on-chain and applies to the
/// pool. Nothing is stubbed: the verifier replays the batch transcript and all
/// five WHIR opening rounds from calldata, and the pool advances both roots
/// from the verified statement. Since D-088 both roots are attested by the
/// proof: the pool stores the statement's `rootAfter` without re-deriving the
/// tree, so `pool_root_after_hex` here cross-checks the circuit's in-circuit
/// Poseidon2 frontier fold against an independent tree walk.
///
/// The proof is read from disk per test rather than cached in a storage
/// variable: a 2.7 MB bytes in storage costs ~84k SSTOREs in setUp, which
/// exhausts the test gas before the interesting part even starts.
///
/// Vectors: block_genesis.json (statement + genesis root + expected root
/// after) + block_composed_bundle.bin, regenerated by:
///   cargo test -p prover --test composed_vectors block_program_equality_and_export -- --ignored
///   node contracts/scripts/gen_composed_flat.mjs block_composed_vectors block_composed_flat
///   node contracts/scripts/gen_bundle.mjs block_composed_flat block_composed_vectors block_composed_bundle
contract BlockE2ETest is Test {
    /// Small sidecar (statement + genesis roots). The full composed export is
    /// tens of MB - parsing it in setUp exhausts EVM memory.
    string internal constant VECTORS = "test/vectors/block_genesis.json";
    string internal constant BUNDLE = "test/vectors/block_composed_bundle.bin";

    ShieldedPool pool;
    uint256[] statement;
    bytes32 expectedRootAfter;

    function setUp() public {
        string memory j = vm.readFile(VECTORS);
        statement = vm.parseJsonUintArray(j, ".statement");

        // Genesis: the pool starts at the root of the tree the block was
        // witnessed against (D-088: the constructor takes the attested root,
        // not leaves to re-hash) and an empty nullifier map (bytes32(0)
        // sentinel: the contract computes the prover's empty root).
        bytes32 genesisRoot = vm.parseJsonBytes32(j, ".genesis_root_hex");
        expectedRootAfter = _asBytes32(vm.parseJsonBytes(j, ".pool_root_after_hex"));

        WhirVerifier verifier = new WhirVerifier(address(new TerminalWeight()), 0xb46b4403210bab3dc9ba9bb906a50408a07443129f274e47c44b722be5f151ec);
        pool = new ShieldedPool(verifier, address(0xB0B), genesisRoot, bytes32(0));
        // H-01: settlement is operator-gated; 0xB0B (the fee recipient) is
        // the seeded operator and admits this test contract.
        vm.prank(address(0xB0B));
        pool.setOperator(address(this), true);
    }

    function _proof() internal view returns (bytes memory) {
        return vm.readFileBinary(BUNDLE);
    }

    function _asBytes32(bytes memory b) internal pure returns (bytes32 out) {
        require(b.length == 32, "digest must be 32 bytes");
        assembly {
            out := mload(add(b, 0x20))
        }
    }

    /// The linchpin: a real block proof verifies and applies. The pool's roots
    /// must land exactly where the prover's own tree says they should.
    function test_real_block_applies_to_the_pool() public {
        pool.applyBlock(statement, _proof());
        assertEq(pool.blockNumber(), 1, "block applied");
        assertEq(pool.currentRoot(), expectedRootAfter, "root matches the prover tree");
    }

    /// A tampered proof byte must not apply.
    function test_tampered_proof_does_not_apply() public {
        bytes memory proof = _proof();
        proof[proof.length / 3] = proof[proof.length / 3] ^ hex"01";
        vm.expectRevert();
        pool.applyBlock(statement, proof);
    }

    /// The LogUp terminal sum is checked fail-fast after the statement check: flip one limb of
    /// terminal 0 and the verification must fail with exactly TerminalSumNonZero
    /// (proving the check fires, not just that some byte matters).
    ///
    /// Terminal word offset inside the bundle: header(4w) + cfgWords + prf len(1w)
    /// + mainDigest(8w) + pv blob(1 len + 87 words) + lookupPow(1w) +
    /// permDigest(8w) + terminal count(1w). All fixed by the block shape.
    /// D-089: the block statement is the folded form - 87 limbs for one
    /// transfer, independent of the child statement's 100.
    function test_tampered_terminal_fails_the_sum_check() public {
        bytes memory proof = _proof();
        uint256 cfgWords;
        assembly {
            // u32 LE at byte 8 -> top byte of the word loaded at m+32+8.
            cfgWords := shr(224, mload(add(add(proof, 32), 8)))
        }
        cfgWords = _swapBytes(cfgWords);
        uint256 termWord = 4 + cfgWords + 1 + 8 + 1 + 87 + 1 + 8 + 1;
        // Sanity: the 6 terminals' limb sums must be zero before tampering.
        // (The honest proof passing test_real_block_applies already proves this.)
        // Data word W sits at file byte 4W: the 16-byte header IS words 0-3.
        uint256 byteOff = termWord * 4;
        proof[byteOff] = proof[byteOff] ^ hex"01";
        vm.expectRevert(WhirVerifier.TerminalSumNonZero.selector);
        pool.applyBlock(statement, proof);
    }

    function _swapBytes(uint256 v) internal pure returns (uint256 o) {
        assembly {
            o := and(shr(24, v), 0xff)
            o := or(o, and(shr(8, v), 0xff00))
            o := or(o, and(shl(8, v), 0xff0000))
            o := or(o, and(shl(24, v), 0xff000000))
        }
    }

    /// A wrong statement limb must not apply.
    function test_wrong_statement_does_not_apply() public {
        statement[statement.length - 1] = statement[statement.length - 1] ^ 1;
        vm.expectRevert();
        pool.applyBlock(statement, _proof());
    }
}
