// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {WhirVerifier} from "../src/verifier/WhirVerifier.sol";
import {ShieldedPool} from "../src/ShieldedPool.sol";

/// The whole point, on one screen: a real shielded block - one client transfer,
/// a real SPHINCS+ spend of a funded note, recursed into the block circuit and
/// settled under the Keccak WHIR config - verifies on-chain and applies to the
/// pool. Nothing is stubbed: the verifier replays the batch transcript and all
/// five WHIR opening rounds from calldata, and the pool advances both roots
/// from the verified statement.
///
/// The proof is read from disk per test rather than cached in a storage
/// variable: a 2.7 MB bytes in storage costs ~84k SSTOREs in setUp, which
/// exhausts the test gas before the interesting part even starts.
///
/// Vectors: block_genesis.json + block_composed_bundle.bin, regenerated by:
///   cargo test -p prover --test composed_vectors block_program_equality_and_export -- --ignored
///   node contracts/scripts/gen_composed_flat.mjs block_composed_vectors block_composed_flat
///   node contracts/scripts/gen_bundle.mjs block_composed_flat block_composed_vectors block_composed_bundle
contract BlockE2ETest is Test {
    /// Small sidecar (statement + genesis roots). The full composed export is
    /// tens of MB - parsing it in setUp exhausts EVM memory.
    string internal constant VECTORS = "test/vectors/block_genesis.json";
    string internal constant BUNDLE = "test/vectors/block_composed_bundle.bin";

    ShieldedPool pool;
    uint256[] statement;
    bytes32 expectedRootAfter;

    function setUp() public {
        string memory j = vm.readFile(VECTORS);
        statement = vm.parseJsonUintArray(j, ".statement");

        // Genesis: the pool starts at the tree the block was witnessed
        // against - the funded note's leaf - and an empty nullifier map
        // (bytes32(0) sentinel: the contract computes the prover's empty root).
        bytes memory leafHex = vm.parseJsonBytesArray(j, ".genesis_leaves")[0];
        bytes32[] memory leaves = new bytes32[](1);
        leaves[0] = _asBytes32(leafHex);
        expectedRootAfter = _asBytes32(vm.parseJsonBytes(j, ".pool_root_after_hex"));

        WhirVerifier verifier = new WhirVerifier();
        pool = new ShieldedPool(verifier, address(0xB0B), leaves, bytes32(0));
    }

    function _proof() internal view returns (bytes memory) {
        return vm.readFileBinary(BUNDLE);
    }

    function _asBytes32(bytes memory b) internal pure returns (bytes32 out) {
        require(b.length == 32, "digest must be 32 bytes");
        assembly {
            out := mload(add(b, 0x20))
        }
    }

    /// The linchpin: a real block proof verifies and applies. The pool's roots
    /// must land exactly where the prover's own tree says they should.
    function test_real_block_applies_to_the_pool() public {
        pool.applyBlock(statement, _proof());
        assertEq(pool.blockNumber(), 1, "block applied");
        assertEq(pool.currentRoot(), expectedRootAfter, "root matches the prover tree");
        assertEq(pool.leafCount(), 2, "genesis leaf + block output");
    }

    /// A tampered proof byte must not apply.
    function test_tampered_proof_does_not_apply() public {
        bytes memory proof = _proof();
        proof[proof.length / 3] = proof[proof.length / 3] ^ hex"01";
        vm.expectRevert();
        pool.applyBlock(statement, proof);
    }

    /// A wrong statement limb must not apply.
    function test_wrong_statement_does_not_apply() public {
        statement[statement.length - 1] = statement[statement.length - 1] ^ 1;
        vm.expectRevert();
        pool.applyBlock(statement, _proof());
    }
}
