// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {WhirVerifier} from "../src/verifier/WhirVerifier.sol";
import {TerminalWeight} from "../src/verifier/TerminalWeight.sol";

/// D-092 M1: the EXISTING verifier pointed at a real multi-layer recursion
/// proof. The bundle is the WBND export of a Fibonacci chain - base proof,
/// two InSC recursion layers, final Keccak settle - generated by:
///   cargo test --release -p prover --test recursion_chain export_chain_bundle -- --ignored
/// The point of this file is the GAS NUMBER: it records what verifying a
/// converged recursion proof costs today (~766 KB postcard -> ~1.35 MB flat
/// at the measured 1.76x ratio), the number the beside-sitting redesign
/// must beat to hit the 30M target. Correctness first: the same accept/reject
/// battery as WhirVerifier.t.sol.
contract RecursionChainE2ETest is Test {
    WhirVerifier internal verifier;
    uint256[] internal statement;

    function setUp() public {
        verifier = new WhirVerifier(address(new TerminalWeight()));
        string memory j = vm.readFile("test/vectors/recursion_chain_sidecar.json");
        statement = vm.parseJsonUintArray(j, ".statement");
    }

    function _bundle() internal view returns (bytes memory) {
        return vm.readFileBinary("test/vectors/recursion_chain_bundle.bin");
    }

    /// The linchpin: a real 2-layer recursion proof verifies under the
    /// existing verifier with no verifier changes (wire-level compatibility,
    /// batch 14). Gas here is the M1 measurement.
    function test_real_recursion_chain_verifies() public view {
        assertTrue(verifier.verify(statement, _bundle()), "chain proof verifies");
    }

    function test_rejects_wrong_statement() public {
        uint256[] memory bad = new uint256[](3);
        bad[0] = 0;
        bad[1] = 1;
        bad[2] = statement[2] + 1;
        vm.expectRevert(abi.encodeWithSelector(WhirVerifier.StatementMismatch.selector, 2));
        verifier.verify(bad, _bundle());
    }

    function test_rejects_tampered_proof() public {
        bytes memory b = _bundle();
        uint256 at = b.length / 3;
        b[at] = b[at] ^ hex"01";
        vm.expectRevert();
        verifier.verify(statement, b);
    }

    function test_rejects_truncated_proof() public {
        bytes memory b = _bundle();
        bytes memory short = new bytes(b.length / 2);
        for (uint256 i; i < short.length; ++i) {
            short[i] = b[i];
        }
        vm.expectRevert();
        verifier.verify(statement, short);
    }
}
