// SPDX-License-Identifier: MIT
// GENERATED by `crates/prover/tests/golden_vectors.rs::transcript_vectors`.
// DO NOT EDIT BY HAND — regenerate with:
//     cargo test -p prover --test golden_vectors transcript_vectors -- --ignored --nocapture
//
// Replays the exact interleaved absorb/sample program the Rust settlement
// transcript performs, asserting every challenge the Solidity challenger
// derives equals the value the Rust prover saw.
//
// Interleaving is the point. Fiat-Shamir is a running hash: absorbing the
// same set of bytes in a different order derives completely different
// challenges while looking correct in review. This file is generated from
// the program that produced the real values, so the order cannot drift.
//
// Note the absorbed bytes are MONTGOMERY forms, not canonical values. The
// statement crossing the settlement boundary is canonical; the transcript
// absorbs Montgomery. See D-045.
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {KeccakChallenger} from "../lib/sol-whir-p3/transcript/KeccakChallenger.sol";

contract TranscriptReplayTest is Test {
    using KeccakChallenger for KeccakChallenger.State;

    /// The whole point of this test: replay the Rust program and land on the
    /// Rust challenges. Any change to the absorb/sample order changes every
    /// subsequent challenge, so this fails loudly rather than drifting.
    function test_replay_matches_rust_challenges() public pure {
        KeccakChallenger.State memory state;

        state.observeBytes(hex"b5c7220a"); // canonical 0xdeadbeef, absorbed as Montgomery
        uint256 s0 = state.sampleBase();
        assertEq(s0, 1934910242, "sample 0 diverges from the Rust transcript");
        state.observeBytes(hex"feffff01"); // canonical 0x1, absorbed as Montgomery
        state.observeBytes(hex"fcffff03"); // canonical 0x2, absorbed as Montgomery
        state.observeBytes(hex"fafbfd05"); // canonical 0xffff, absorbed as Montgomery
        uint256 s1 = state.sampleBase();
        assertEq(s1, 935446202, "sample 1 diverges from the Rust transcript");
        // Proof-of-work: absorbing the witness must zero the next 4 bits.
        state.observeBytes(hex"f2ffff0d");
        assertEq(state.sampleBitsUnchecked(4), 0, "PoW witness does not satisfy the challenge");
    }
}
