//! Golden vectors for the on-chain Merkle accumulator.
//!
//! The Solidity `MerkleAccumulator` re-implements the same tree the Rust
//! `CommitmentTree` defines, using an MMR-style fold instead of the full
//! recursion. If the two ever disagree, every block settlement fails — so the
//! equivalence is asserted here rather than eyeballed, and the vectors are
//! written to `contracts/test/vectors/` for the Foundry tests to consume.

use pq_hash::{CommitmentHasher, Digest32, Keccak256Commitment, NoteHash};
use shielded::tree::{CommitmentTree, DEPTH};

/// Mirror of the Solidity accumulator: `branch[h]` holds the most recently
/// closed complete subtree of height `h`, present iff bit `h` of the count is
/// set. Deliberately written the way the contract is written, not the way the
/// Rust tree does it, so a divergence shows up as a test failure.
struct SolAccumulator<'a> {
    hasher: &'a Keccak256Commitment,
    count: usize,
    branch: Vec<Digest32>,
}

impl<'a> SolAccumulator<'a> {
    fn new(hasher: &'a Keccak256Commitment) -> Self {
        Self {
            hasher,
            count: 0,
            branch: vec![Digest32::default(); DEPTH + 1],
        }
    }

    fn append(&mut self, leaf: Digest32) {
        let mut cur = leaf;
        let mut h = 0usize;
        while h < DEPTH && ((self.count >> h) & 1) == 1 {
            cur = self.hasher.hash_pair(&self.branch[h], &cur);
            h += 1;
        }
        assert!(h < DEPTH, "tree full");
        self.branch[h] = cur;
        self.count += 1;
    }

    fn root(&self) -> Digest32 {
        let mut cur = Digest32::default();
        let mut empty = Digest32::default();
        for h in 0..DEPTH {
            if h > 0 {
                empty = self.hasher.hash_pair(&empty, &empty);
            }
            if ((self.count >> h) & 1) == 1 {
                cur = self.hasher.hash_pair(&self.branch[h], &cur);
            } else {
                cur = self.hasher.hash_pair(&cur, &empty);
            }
        }
        cur
    }
}

#[test]
fn solidity_accumulator_matches_rust_tree() {
    let hasher = Keccak256Commitment;
    let leaf = |b: u8| Digest32::new([b; 32]);

    let mut rust = CommitmentTree::new(hasher);
    let mut sol = SolAccumulator::new(&hasher);

    // Empty tree first: the fold must reproduce the all-empty root.
    assert_eq!(
        sol.root().as_bytes(),
        rust.root().as_bytes(),
        "empty root mismatch"
    );

    // Cross a several power-of-two boundaries: 1, 2, 3, 4, 8, 9. Those exercise
    // every branch of the merge loop and the padding path.
    for n in 1..=9usize {
        let l = leaf(u8::try_from(n).expect("test leaf index fits in u8"));
        rust.append(&NoteHash::from_digest(l));
        sol.append(l);
        assert_eq!(
            sol.root().as_bytes(),
            rust.root().as_bytes(),
            "root mismatch at N = {n}"
        );
    }
}

#[test]
fn emit_contract_vectors() {
    let hasher = Keccak256Commitment;
    let leaf = |b: u8| Digest32::new([b; 32]);

    let mut lines = vec!["{".to_string()];
    lines.push(
        "  \"note\": \"Generated by crates/shielded/tests/contract_vectors.rs\",".to_string(),
    );
    lines.push("  \"depth\": 32,".to_string());
    lines.push("  \"cases\": [".to_string());

    // Empty root, then one case per append with the leaf and the root it yields.
    // Cumulative cases: each entry lists every leaf appended so far and the root
    // the tree has after them. A contract test replays the whole list from an
    // empty tree, so each case exercises a batch append of that size.
    let mut tree = CommitmentTree::new(hasher);
    let mut cases: Vec<(Vec<String>, String)> = Vec::new();
    cases.push((vec![], hex::encode(tree.root().as_bytes())));
    let mut seen: Vec<String> = Vec::new();
    for n in 1..=5usize {
        let l = leaf(u8::try_from(n).expect("test leaf index fits in u8"));
        tree.append(&NoteHash::from_digest(l));
        seen.push(hex::encode(l.as_bytes()));
        cases.push((seen.clone(), hex::encode(tree.root().as_bytes())));
    }
    for (i, (leaves, root)) in cases.iter().enumerate() {
        let joined = leaves
            .iter()
            .map(|l| format!("\"{l}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let comma = if i + 1 == cases.len() { "" } else { "," };
        lines.push(format!(
            "    {{ \"leaves\": [{joined}], \"root\": \"{root}\" }}{comma}"
        ));
    }
    lines.push("  ]".to_string());
    lines.push("}".to_string());

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/test/vectors/merkle.json"
    );
    std::fs::write(path, lines.join("\n") + "\n").expect("write vectors");
}
